import type { Metadata } from "next";
import {  Manrope} from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";


const manrope = Manrope({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Nav />
        <main className="md:pl-28 md:py-[58px] pt-[40px] pb-[120px] ">

        {children}
        </main>
      </body>
    </html>
  );
}
